apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-mcp-server-9698455b8-6l76z
  namespace: github-mcp
spec:
  template:
    spec:
      containers:
      - name: <container-name>
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
