apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcpo-6c45b597f7-r8974
  namespace: mcpo
spec:
  template:
    spec:
      containers:
      - name: <container-name>
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
