apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-redis-778c7974f5-d7wxr
  namespace: open-webui
spec:
  template:
    spec:
      containers:
      - name: <container-name>
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
